runtime: python39

entrypoint: streamlit run app.py --server.port $PORT

# Optional: specifying an instance class
instance_class: F2

# Environment variables
env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ENABLE_CORS: "false"

# Optional: enable automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2